### ISSUE TITLE
Fix font size in two different sections

### ISSUE THREAD

**Issue by imanishbarnwal** [hack4bengal/s3#10]
Fix Padding and font size

![image](https://github.com/hack4bengal/s3/assets/46371923/d559e204-071d-48f5-8389-4390a7cb1d22)

**Comment by Muhammad-Shahid-Jamal** [comment]
Hi plz assign this issue to me so i can contribute to it. Thanks

**Comment by ShrutiKolla** [comment]
@imanishbarnwal can you please assign this to me?

**Comment by imanishbarnwal** [comment]
Hi @Muhammad-Shahid-Jamal I have assigned it to you kindly start working, and thanks @ShrutiKolla for your interest but kindly look for other issues I will assign you. :D
