### ISSUE TITLE
[FEATURE] Adding vite to the existing app

### ISSUE THREAD

**Issue by tamalCodes** [hack4bengal/s3#13]
Currently we are using the good old `create-react-app` however that is not recommended at all. It would be much faster if we could integrate `Vite` to it. Here's a guide for the same.

[Adding vite to react webapps](https://joshuaclaudioenrico.medium.com/why-vite-and-how-to-migrate-a-existing-react-aplication-cd1b38d10220), please use this guide for the same.

**Comment by sayakongit** [comment]
@tamalCodes I can work on this.

**Comment by tamalCodes** [comment]
Please go ahead, we are taking up one issue at a time so your comment on another issue will be ignored OR marked as `outdated` for the time being. Please make sure to make a proper PR with full detailed changes written, thanks 🤘🏻

**Comment by sayakongit** [comment]
> Please go ahead, we are taking up one issue at a time so your comment on another issue will be ignored OR marked as `outdated` for the time being. Please make sure to make a proper PR with full detailed changes written, thanks 🤘🏻

Sure! Thanks
