### ISSUE TITLE
[BUG] Cleanup of teams page and assets

### ISSUE THREAD

**Issue by tamalCodes** [hack4bengal/s3#14]
- The `/team` page will not be used anymore please remove that from the website, including the route for it
- Remove the `Meet our team` section from the  homepage too

**Comment by nishantdub37** [comment]
@tamalCodes can u assign this to me?

**Comment by sayakongit** [comment]
Hey @tamalCodes, can you assign this to me?

**Comment by rkd-sh64** [comment]
#### @tamalCodes I would like to work on this

**Comment by tamalCodes** [comment]
Please go ahead @rohits-web03 , do make a proper detailed PR once this is done.

**Comment by apneduniya** [comment]
Hey I am interested!!

**Comment by apneduniya** [comment]
As no one is assigned this issue I am doing this

**Comment by rkd-sh64** [comment]
#### @tamalCodes Should I delete all the files related to team page? or just modify the code in such a manner that the /team page doesn't show up in the website and the files related to it remain in the repo?

**Comment by rkd-sh64** [comment]
> Please go ahead @rohits-web03 , do make a proper detailed PR once this is done.

@apneduniya I am already working on this issue

**Comment by tamalCodes** [comment]
> #### @tamalCodes Should I delete all the files related to team page? or just modify the code in such a manner that the /team page doesn't show up in the website and the files related to it remain in the repo?

The files can be deleted except the images.

**Comment by apneduniya** [comment]
It was just assigned now and I already raised the [PR](https://github.com/hack4bengal/s3/pull/16) 😞
