### ISSUE TITLE
Create a "Past Sponsors" Section on the Website

### ISSUE THREAD

**Issue by imanishbarnwal** [hack4bengal/s3#18]
In order to maintain an updated and organized website for our hackathon, we need to create a "Past Sponsors" section to showcase our sponsors from [Season 2](https://s2.hack4bengal.tech/) and [Season 1](https://s1.hack4bengal.tech/). Currently, the website displays the "Sponsors & Partners" section as `To be decided soon...`, and we would like to replace the Sponsors & Partners to Past Sponsors to give them the recognition they deserve.

![image](https://github.com/hack4bengal/s3/assets/46371923/d81ec95e-6c68-4977-b107-dd778810f3e2)

**Comment by rkd-sh64** [comment]
#### Where can I find the info related to past sponsors?

**Comment by imanishbarnwal** [comment]
I have linked the past website's links, you can get the sponsors list from there

**Comment by rkd-sh64** [comment]
Okay
I would like to work on this.
Can you assign me?

**Comment by imanishbarnwal** [comment]
Sure, I have assigned this to you

**Comment by rkd-sh64** [comment]
> I have linked the past website's links, you can get the sponsors list from there

In [Season 1's website](https://s1.hack4bengal.tech/) the sponsors are not categorized into platinum,gold,silver or MLH like in season 2
So for Season 1 should I keep all the sponsors together without categorizing them?

**Comment by imanishbarnwal** [comment]
Don't categorize sponsors, put everyone under one section that's past sponsors that's it. Put them in a sequence of 1st put season 2 sponsors serially, then season 1 sponsors also please skip common sponsors from the list

**Comment by rkd-sh64** [comment]
@imanishbarnwal @tamalCodes 
I have made the changes you asked for.
Would really appreciate if you can review the changes #35
