### ISSUE TITLE
Testimonials LinkedIn Id link not working

### ISSUE THREAD

**Issue by rajdeepbuilds** [hack4bengal/s3#21]
Can i work on this issue?

**Comment by tamalCodes** [comment]
Sure go ahead !
Would be great if you could link the correct LinkedIn accounts 🚀

**Comment by rajdeepbuilds** [comment]
Thank You @tamalCodes

**Comment by rajdeepbuilds** [comment]
It's done 
Kindly check @tamalCodes

**Comment by rajdeepbuilds** [comment]
This issue has been resolved.
