### ISSUE TITLE
Bug: Changes to mentors section

### ISSUE THREAD

**Issue by tamalCodes** [hack4bengal/s3#22]
![image](https://github.com/hack4bengal/s3/assets/72851613/bef7bafe-4af1-42fb-9bdb-bf5f683a3422)

Take a look at the picture above, as you can see there is an inconsistent flow. Please change the id from `#/judges` to `#/mentors`. This is a very small issue, great for beginners !

**Comment by taran1326** [comment]
Hey I can fix the issue, can you assign me the issue ?

**Comment by tamalCodes** [comment]
Sure, go ahead @taran1326 . Make sure to make a proper PR.

**Comment by taran1326** [comment]
Hey @tamalCodes when I setup the project on local machine More option is not working ? did I miss something ?

**Comment by alok5050** [comment]
Can you please assign me this issue, I would like to work on it?

**Comment by tamalCodes** [comment]
> Hey @tamalCodes when I setup the project on local machine More option is not working ? did I miss something ?

It should work out of the box. Please check again, or try to reinstall again

**Comment by taran1326** [comment]
Yes it worked.

**Comment by taran1326** [comment]
Its done. Can you please check @tamalCodes ?
