### ISSUE TITLE
Bug: Hero section button issue

### ISSUE THREAD

**Issue by tamalCodes** [hack4bengal/s3#23]
![image](https://github.com/hack4bengal/s3/assets/72851613/fb7636f1-812c-4143-aa95-e06a786e3bfb)

The whole button element is not an anchor tag. If i click outside the `Join discord` text nothing will happen which is a very bad usecase. Please ensure that the whole element /button takes me to the desired page when clicked.

A great issue for beginners to jump in !

**Comment by strive79** [comment]
Hey,

I would like to work on this , Kindly assign this to me .
Thanks

**Comment by Virtual4087** [comment]
I would love to work on this issue

**Comment by tamalCodes** [comment]
Sure, go ahead @Shubhangam333. Make sure to make a proper PR.

**Comment by strive79** [comment]
#24 Raised this PR for the fix . Thank you for providing me this opportunity to make contribution for this project
