### ISSUE TITLE
Update Contributing.md file

### ISSUE THREAD

**Issue by sayakongit** [hack4bengal/s3#28]
## Description

The current Contributing.md file seems old and contains the old repo name in places. We should also add how to start the server. 

## Screenshot

![image](https://github.com/hack4bengal/s3/assets/83216382/693c26c7-6d51-4f0d-b894-0a16a16d2648)

**Comment by taran1326** [comment]
I will do it , can you please add hacktoberfest tag ?

**Comment by imanishbarnwal** [comment]
Sure, please go ahead
