### ISSUE TITLE
Build a new UI/UX for Season 3

### ISSUE THREAD

**Issue by imanishbarnwal** [hack4bengal/s3#3]
Consider updating the overall User Interface (UI) and User Experience (UX) design for the Hack4Bengal Season 3 website. This issue focuses on evaluating the current design, gathering feedback, and proposing a new UI/UX to enhance the website's visual appeal, user-friendliness, and overall engagement. You can recommend design changes, create wireframes, and eventually implement a refreshed UI for the upcoming season.

**Comment by eugeneanokye99** [comment]
can you please assign me

**Comment by imanishbarnwal** [comment]
Sure @eugeneanokye99
