### ISSUE TITLE
Bug: Navbar Menu on mobile devices is not organized

### ISSUE THREAD

**Issue by tushar-daiya** [hack4bengal/s3#31]
The navbar menu on mobile devices seems not organized and there are two live options in the nav menu.
![www hack4bengal tech_(iPhone 12 Pro)](https://github.com/hack4bengal/s3/assets/108505673/ba560c77-5014-493a-b286-3cb537cba7e1)

Can i work on this?

**Comment by imanishbarnwal** [comment]
Sure, you can work on this
