### ISSUE TITLE
Bug: Remove first two logos

### ISSUE THREAD

**Issue by tamalCodes** [hack4bengal/s3#38]
We would need some change in the brand assets, you can access the page in [hack4bengal.tech/brand](https://www.hack4bengal.tech/brand), where we would remove the first two logos.

- Hack4Bengal Wide Govt. Infused Logo Light
- Hack4Bengal Wide Govt. Infused Logo Dark

![image](https://github.com/hack4bengal/s3/assets/72851613/8eb3dbe7-f936-4b60-a34a-aaf003737e68)

**Comment by jude-san** [comment]
please assign to me @tamalCodes

**Comment by AlexiusTatius** [comment]
@tamalCodes sir I have solved the issue. 
Can you please review my pull request?
