### ISSUE TITLE
Create/modify Event Page for Hack4Bengal Season 3 Website

### ISSUE THREAD

**Issue by imanishbarnwal** [hack4bengal/s3#4]
We need to create a dedicated Event Page on the Hack4Bengal Season 3 website to provide comprehensive information about the upcoming online/IRL events by Hack4Bengal. This page will serve as a central hub for all things related to all the events either it's past or future events. The Event Page should be user-friendly, visually appealing, and highly informative to engage participants effectively.

Earlier, we had created a page that was not completed yet, [check here](https://www.hack4bengal.tech/events) if you can help us to improve it.

**Comment by KaiAlan** [comment]
Hello @imanishbarnwal 
I want to work on this so, I was wondering do I need to design it from scratch or do you have some designs that I need to implement?

**Comment by imanishbarnwal** [comment]
No, we don't have any designs you can refer to other community events or pages. You have to think & design it from scratch. I am assigning this to you. Thank :)

**Comment by KaiAlan** [comment]
Thank you for assigning this to me. I will let you know once the design is complete for your approval.

**Comment by KaiAlan** [comment]
Hi @imanishbarnwal, here is the outline of the sections in event page i come up with. Please review this and let me know for any modifications to made


## H4B-s3 Event Page

### Navigation

- [Home](#)
- [About](#)
- [Schedule](#)
- [Prizes](#)
- [Sponsors](#)
- [FAQs](#)
- [Contact Us](#)

### Hero Section

   - A captivating image or video related to hackathon
   - A concise and compelling headline
   - A clear call-to-action (CTA) button for registration
  
### Countdown Timer

   - a countdown timer to build anticipation

### About the Hackathon

   - A brief description of the hackathon's history (mentioning the first two seasons)
   - The purpose and goals of the event
   - Any unique selling points (e.g., themed challenges, special guests)

### Schedule

   - A detailed event schedule, including key activities, workshops, and deadlines

### Prizes and Awards

   - List of prizes and awards for participants
   - Description of how winners will be selected
   - Information about sponsor contributions

### Sponsors

   - Logos and brief descriptions of event sponsors
   - Highlight the benefits of sponsorship and how to become a sponsor

### FAQs

   - Commonly asked questions and answers
   - Information about eligibility, registration, judging criteria, etc.

### Rules and Guidelines

   - Detailed rules and guidelines for participants
   - Code of conduct and ethics

### Team and Judges

   - Information about the organizing team
   - Profiles of judges and mentors

### Registration

   - A prominent CTA button to register for the event

### Testimonials

   - Quotes or stories from previous participants or sponsors
   - Highlight the positive experiences of past hackathons

### Contact Information

   - Contact details for inquiries and support
   - Links to your social media profiles

### Footer

   - Copyright information
   - Links to the privacy policy and terms of service

### Social Sharing and Engagement

   - Share buttons to encourage visitors to promote the event on social media
   - Links to your social media profiles for engagement

### Media Gallery

   - Photos and videos from previous hackathons

### Blog/News Section

   - A section for updates and news related to the event

**Comment by KaiAlan** [comment]
![Theme style](https://github.com/hack4bengal/s3/assets/91906702/2071c2cb-2f7f-4bdb-8ebe-b594f9a051a8)

This above is the background theme and the wheel on the right side will open up the navigation menu

do you have any specific theme for designing of site?
if not i will like to suggest the pirate theme for the design, where :

-hero section will have a pirate theme touch to it
-prize section will show different treasure boxes according to prize,
-venue will show a treasure map which on click will redirect to google map,
-and all the other section will have design specific to the theme too

and obviously, all will follow the the already present color palette of h4b

Let me know what you think about it...

**Comment by imanishbarnwal** [comment]
This is for event page specifically @KaiAlan or for the whole if it's for the whole website then here's the existing issue #3 but I like the idea we can discuss on this

**Comment by KaiAlan** [comment]
@imanishbarnwal the issue #3 is already assigned. so i believe this is for event page specifically.

and yes I'll also like to discuss further, will Discord be okay for you?
if yes, I'll dm all the details and progress in discord to you

**Comment by imanishbarnwal** [comment]
Both you can work on that issue I will assign it you can start working. And later we can schedule a call...

**Comment by KaiAlan** [comment]
Very well, btw I have sent you some more details and progress in discord pls have a look on that too🥺
