### ISSUE TITLE
An PWA For official Website 

### ISSUE THREAD

**Issue by Shinjan-saha** [hack4bengal/s3#44]
I propose  that an Web-App which will  work on both online & offline will increase the effectiveness & the purpose of the Website

**Comment by Shinjan-saha** [comment]
please assign this issue to me @imanishbarnwal   @tamalCodes

**Comment by Shinjan-saha** [comment]
It has been 1 week since i put this issue is anyone active anymore in this project?

**Comment by tamalCodes** [comment]
Hi there, sorry about the delay. Was busy with exams and a lot of things happening at once. The idea is amazing; what changes do you propose to make the web-app function offline/caching too ?

**Comment by Shinjan-saha** [comment]
yes that's the Idea so people can also see the content of website as an App when offline also

**Comment by tamalCodes** [comment]
> yes that's the Idea so people can also see the content of website as an App when offline also

I understand all I wanted to ask is Are you looking forward to working on some caching techniques like implementing service workers or something like that 

I would love to know about the approach you were about to take in order to code this out or is this just an issue that you raised for us to develop.

**Comment by Shinjan-saha** [comment]
Ok So there will be total 3 things needs to be done to make an web-app in all total

1) Serviceworker.js:- Which will make the app installable &  will create the cache where we will make the pages & all it's assets available  offline 

2) Manifest.json:- Where we will give the app details such as it's Logo & name 


3) Javascript:-  Where we will  write an JS  code access the serviceworker in browser & make the app installable & we will have an option  to download the app from browser.


And all of these Files & changes will be made in the  "public" directory of the React Project

**Comment by tamalCodes** [comment]
Okay are you willing to contribute to the code ?

**Comment by Shinjan-saha** [comment]
yes i am Willing to code it please assign this issue to me
@tamalCodes

**Comment by Shinjan-saha** [comment]
If this is Okay can i please get this issue assigned @tamalCodes

**Comment by tamalCodes** [comment]
> If this is Okay can i please get this issue assigned @tamalCodes

Yes you can start to work on it, I did assign you but I guess there was some issues

**Comment by Shinjan-saha** [comment]
https://s3-pwa-trail.vercel.app/

I have deployed the App over here for PWA can you please check it & let me know how it is  @tamalCodes

**Comment by tamalCodes** [comment]
I'd recommend you to make a PR for better reviews, it'll get auto deployed for testing and for others to see,
Also note that we have had some significant changes.

**Comment by Shinjan-saha** [comment]
@tamalCodes  I have created the PR
