### ISSUE TITLE
Bug: Improving acessibility of the website

### ISSUE THREAD

**Issue by tamalCodes** [hack4bengal/s3#48]
### Description

Currently, as you can see the accessibility score is pretty low, the issue is to make this score as high as possible.

- Some image elements do not have an alt tag
- Some image elements have alt tags but the description is very much different than what it should be
- The Links do not have a discernible name

### Proposed Solution

- You can generate the alt tags using [alt-text generator](https://alttext.in/)
- You can add `aria-label` or research more about how to make links accessible

### Screenshots

![image](https://github.com/hack4bengal/s3/assets/72851613/245dd61f-6b62-49b2-a3b4-69160e83636e)

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/hack4bengal/s3/issues)
- [ ] I am willing to work on this issue (blank for no).

**Comment by harith-hacky03** [comment]
I am eager to solve it . Can i?

**Comment by tamalCodes** [comment]
Sure go ahead. Make sure to make proper PR names like `[FIX]: dadada sdkn sad`
Do let me know once you are done. This is a high priority issue and must be solved quickly

**Comment by harith-hacky03** [comment]
@tamalCodes  I almost completed the static alt but this footer_bg link is not found can you please check it out .
Link : https://www.hack4bengal.tech/assets/footer_bg-5b4bb7e1.svg

**Comment by harith-hacky03** [comment]
@tamalCodes  Everything is done and i submitted my PR check it out . Let me know if things needs to be changed .
Thank you so much .
