### ISSUE TITLE
Bug: Improving the SEO of the whole website

### ISSUE THREAD

**Issue by tamalCodes** [hack4bengal/s3#49]
### Description

The SEO score for the website can be improved a lot. The site must be crawlable and have proper details and matching keywords.

### Proposed Solution

- Some images do not have a proper alt tag make sure most of the images have alt tags that are matching with the description. You can generate alt tags by using the following generator.
- The links are not crawlable to appear in search results the links must be crawled
- Different pages must have different proper meta types make sure the website has proper meta tags.

### Screenshots

![image](https://github.com/hack4bengal/s3/assets/72851613/dfbb884c-c2bc-4c2d-9cc5-e1d42780b01d)

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/hack4bengal/s3/issues)
- [ ] I am willing to work on this issue (blank for no).

**Comment by harith-hacky03** [comment]
I am ready to do it too . Can you assign me?

**Comment by tamalCodes** [comment]
Hi there @harith-hacky03 , go ahead !

The search engine optimization as of now looks good and the score is coming out to be a perfect 100 but there might be some minor changes that are needed to modify the site's search engine optimization a little bit more.

**Comment by harith-hacky03** [comment]
@tamalCodes Its 100% already , Can you please say are the changes i want to make?

**Comment by tamalCodes** [comment]
Not sure either, i'll close the issue for now.
