### ISSUE TITLE
Add Pre-Registration Form and Remove "Application Closed" Button

### ISSUE THREAD

**Issue by imanishbarnwal** [hack4bengal/s3#5]
To facilitate pre-registration for Hack4Bengal Season 3, we need to add a Pre-Registration Form to the event website. This will replace the "Application Closed" button, making it easier for prospective participants to express their interest in the hackathon before official registration opens.

Here's the pre-registration link: https://bit.ly/h4bs3-pre-registration

**Comment by Damon248** [comment]
Hello, @imanishbarnwal! I would like to work on this issue, can you please assign this to me?

**Comment by imanishbarnwal** [comment]
Sure @Damon248 go ahead

**Comment by Damon248** [comment]
I have made the required changes, can you please check out my pull request?

**Comment by Shinjan-saha** [comment]
I have done the PR & solved this Issue please merge it 
 #1 
Thank You

**Comment by imanishbarnwal** [comment]
I have dropped an update on your PR @Shinjan-saha kindly get it assigned before working on it, and thanks @Damon248 your PR is merged.
