### ISSUE TITLE
Bug: Enhancing the performance of the website

### ISSUE THREAD

**Issue by tamalCodes** [hack4bengal/s3#50]
### Description

The website has a decent level of performance however that can be improved a lot more by adding different functionalities and making sure to include best practices. [DETAILS.](https://pagespeed.web.dev/analysis/https-www-hack4bengal-tech/6nn8h3ecss?form_factor=desktop). A lot of details on how this can be done are mentioned in the link that is provided.

### Proposed Solution

- Make sure the Image elements have explicit width and height. 
- Preloading LCP elements.

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/hack4bengal/s3/issues)
- [ ] I am willing to work on this issue (blank for no).

**Comment by sayakongit** [comment]
Hi @tamalCodes if this issue is still open, I would like to work on this.

**Comment by tamalCodes** [comment]
Hi @sayakongit The websites performance is looking pretty good to me do you find anything that can be improved please let me know in the comments
