### ISSUE TITLE
Bug: FAQ section is overflowing at & above 576px of screen size.

### ISSUE THREAD

**Issue by SnehansuBehera** [hack4bengal/s3#86]
### Description

The FAQ section is not responsive and overflowing out of the container at and above 576px of screen width.

### Proposed Solution

The FAQ section should be made responsive for every screen sizes like other sections in the website

### Screenshots

![Screenshot 2024-05-24 140249](https://github.com/hack4bengal/s3/assets/121883802/542e9037-e5b3-4e85-9ef2-474faebd0f61)
![Screenshot 2024-05-24 140256](https://github.com/hack4bengal/s3/assets/121883802/3a040996-f1fc-46db-8764-a94d5976a5ba)

@tamalCodes I would like to contribute to it. please allow me. I have been an active contributor in GirlScript Summer of Code 2024.

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/hack4bengal/s3/issues)
- [X] I am willing to work on this issue (blank for no).

**Comment by tamalCodes** [comment]
Hey @SnehansuBehera we would love to have you contribute for Hack4Bengal - do you know why this behaviour is occurring ?

**Comment by SnehansuBehera** [comment]
> Hey @SnehansuBehera we would love to have you contribute for Hack4Bengal - do you know why this behaviour is occurring ?

I observed couple of classes were given with arbitrary fixed widths:
1.  .faq_content class is given fixed width of 69.95rem 
2.  .container class is given fixed width of 48rem
These are the reasons which is breaking the section UI making everything overflow, creating a horizontal bar.

I have resolved the issue should i make the pr @tamalCodes 

![Screenshot 2024-05-26 222527](https://github.com/hack4bengal/s3/assets/121883802/f4c042e8-cb1f-4d0c-952b-4fea3f1d199e)
![Screenshot 2024-05-26 222557](https://github.com/hack4bengal/s3/assets/121883802/7108a528-d527-4e43-b3da-7648697724f5)
![Screenshot 2024-05-26 222309](https://github.com/hack4bengal/s3/assets/121883802/f5d2e390-8c6c-42e9-b77b-86cc615b512e)

**Comment by SnehansuBehera** [comment]
@tamalCodes I would love to contribute further in the website. please let me know where i can chip in.

**Comment by tamalCodes** [comment]
Hey @SnehansuBehera sure, Thank you so much for your hard work - Yes our code is Opensource , feel free to contribute whenever you find issues !
