### ISSUE TITLE
Improve the carousel in past mentors section

### ISSUE THREAD

**Issue by kajal1801** [hack4bengal/s3#9]
Add some new effects to the carousel and improve the design as well.

**Comment by sushma1031** [comment]
Hello, I'd like to work on this, could you please assign it to me?

**Comment by imanishbarnwal** [comment]
Hi @sushma1031 I have assigned it to you, you can start working on it. Also, check the mentors and testimonial section in mobile devices and fix that as well. Thank You :)

**Comment by sushma1031** [comment]
@imanishbarnwal hello, I'm sorry, I won't be able to work on this.

**Comment by AlapanDas** [comment]
@imanishbarnwal I would like to work on this issue, assign me on this issue

**Comment by imanishbarnwal** [comment]
Done @AlapanDas , all the best
